### PR TITLE
PR #32 (add/renderMetaBox)

### PR DESCRIPTION
**Pull request by rgadon107**
@hellofromtonya Hi! I created this branch to start work on the unit & integration tests for the function `render_meta_box`. I know I'm getting closer to completing the first test because the error messages are changing. 

I was stuck on how to mock the `WP_Post` class object, which is the first argument of the function under test. Later I realized it could be mocked with Mockery, which I've not used before. 

Currently, the error message I'm receiving is: 

>Mockery\Exception\InvalidCountException: Method get_instance(47) from Mockery_1__WP_Post should be called exactly 1 times but called 0 times.

The object's method `get_instance` is supposed to run once, but isn't running at all. Can you help me to fix this problem? I know that our `Test_Case` uses `MockeryPHPUnitIntegration`. Do I need to declare that as well at the top of the `renderMetaBox` unit test file? Or does class `Tests_RenderMetaBox` inherit that from class `Test_Case`?

I know this is a complicated test. If I'm missing anything, or have something incorrectly configured, please point that out. Thanks.

### CODE REVIEW

**Comment by hellofromtonya** [comment]
@rgadon107 There are many different things to test in the rendering a meta box. Here's a strategy for you:

1. Test each part what gets rendered based upon whatever inputs and processing happens within the function, i.e. the expected HTML that gets generated.
2. You need to use PHP's output buffer to capture and return the rendered HTML. Then you can test against what actually gets sent out to the browser against what you expected that HTML to be.

This PR introduces you to many new testing concepts. Therefore, to help you see what steps to take, I went ahead and created the unit tests for you.  Another great resource you can use is what we built in Beans. You can see how we leverage the output buffer in both [integration](https://github.com/Getbeans/Beans/blob/c550d23e7073209c4e6b6e21f2a01906d7bd0dbf/tests/phpunit/integration/api/html/beansOpenMarkupE.php) and [unit tests](https://github.com/Getbeans/Beans/blob/c550d23e7073209c4e6b6e21f2a01906d7bd0dbf/tests/phpunit/unit/api/html/beansOpenMarkupE.php).

**Comment by rgadon107** [comment]
@hellofromtonya I've been looking intensively through the unit tests that you built for this PR. There are _so many_ components in the render function. My initial submittal was trying to do too much in one method. I clearly had not isolated enough of the components to focus on the behavior of one single component. Nice and effective use of PHP's output buffer as the foundation to make comparisons in the test assertions. 

I'm running into a problem with getting my first integration to run properly. I've tried a number of different ways to instantiate a post object or call the post ID. Ultimately, I reverted back to my initial code. The error message I'm getting on the command line is: 

> Whoops\Exception\ErrorException: Missing argument 1 for WP_Post::__construct(), called in `/app/public/wp-content/mu-plugins/central-hub/tests/phpunit/integration/meta-data/renderMetaBox.php` on line 42 and defined `/tmp/wordpress/wp-includes/class-wp-post.php`; L#264

I'm not sure what argument or value I'm supposed to pass to the `__construct()` method to instantiate a new WP_Post object. Can you help me solve this problem?

**Comment by rgadon107** [comment]
@hellofromtonya What a difference a week away from this project makes. I sat down today and worked through the first integration test. Once I figured it out, the remaining 3 tests came fairly easily. 

I renamed the 3 view files stored in the `tests/fixtures` folder to describe whether they accept either a `$meta_box_id` or `$custom_fields[ $meta_key ]` input or both. 

Any refactoring of the integration test file that you think would be useful for improved readibility would be welcome. The integration test methods are _long_ (or at least they seem that way to me after staring at them for so long).

**Comment by rgadon107** [comment]
@hellofromtonya I created several new properties in the unit test file for class `Tests_RenderMetaBox`, and called them from the class object inside each test method. That removed several lines of code, particularly in the last test. 

I had trouble passing $this->nonce_html to the closure used to mock the return value of `Monkey\Functions\expect( 'wp_nonce_field' )`. PHPStorm nagged at me and PHPUnit expected that I pass a string, not an object. ;-(  So I just reverted to what you originally created. 

In the third unit test ( `test_should_render_wp_nonce_field()` ), I wanted to declare `$this->nonce_html` within the method scope, and then pass that to the _use_ language construction in the the closure. For example: 

>Monkey\Functions\expect( 'wp_nonce_field' )
			->once()
			->with( 'events_nonce_action', 'events_nonce_name' )
			->andReturnUsing( function () use ( $this->nonce_html ) {
				echo $this->nonce_html;
			} );

Unfortunately, PHP doesn't allow that. So the test method is little more verbose. It still works.

**Comment by rgadon107** [comment]
Lessons learned from this pull request ( created 08/29/2019 by `rgadon107` ): 

**1) Mockery versus Brain Monkey** — Use Mockery to mock objects and Brain Monkey to mock functions. In this PR, the function under test accepted an instance of the WP_Post object as an argument. Brain Monkey is not configured to mock objects. Therefore, I needed to consult the Mockery documentation and mock the WP_Post object for the unit test.
The simplest way to mock WP_Post was to pass it as argument to Mockery’s ‘mock()’ method, then assign that method to a variable.

**2) Declare class properties** — How to extend the unit test class using OOP and declare protected properties ( e.g. $post, $meta_config, and $meta_box_args ) of the class ‘Tests_RenderMetaBox’ for later use in each test method.

**3) $this** — Apply the use of $this to access the properties and methods of an object. It was a bit confusing at first to understand what $this meant as it abstracts away the details of an object.

**4) When to load a meta box config into __the_store_** — For the unit tests on this branch, it was not necessary to generate a complete meta_box configuration and load it into the data store. That was only needed in the integration tests. Instead, declare a $meta_config property in the test class, initialize the property in the setUp() method, and modify the property when needed in a specific test.

**5) Planning the design of each test** — Think through each of the tasks performed within the function under test and write a separate method to test that specific task in isolation of the rest of the tasks.

**6) Buffer HTML** — Use PHP’s output buffer to capture the HTML from a view file. The buffer output can be compared to HTML within the test method.

**7) What to add to the buffer** — Dependent functions that generate their own HTML should be passed to and cleared from an output buffer in order to compare the value from the buffer via a test assertion.

**8) Use fewer fixtures when possible** — Use a single dynamic view file for the integration test rather than multiple files. The point of the tests is to exercise the code that builds the HTML and renders it out. A single file allows us to check that the meta_box_id and custom field values are passed to the view, and simplifies the number of view files to track.

**9) Simplify the fixture view file when possible** — Simplify the fixture view file enough to ensure that the assigned variables or return values of dependent functions are loaded into the view as expected.

**10) Assign a value to the property of an object** — When a function under test (or one of it’s dependencies) requires the property of an object as an argument, assign that property a value. Otherwise, the property is null (has no value). For example:

// Correct
$this->post          = m::mock( ‘WP_Post’ );
$this->post->ID   = 99;  // ID = 99.

//Incorrect
$this->post          = m::mock( ‘WP_Post’ );
$this->post->ID      // null. ID is not assigned a value.

**11) Use WordPress factories to create and get data objects** — In integration tests, WordPress installs an empty database. Data objects (e.g. $post, $user, $comment) are often required to perform a test. WordPress provides fixtures to generate these objects, which are generated by factories. In this PR, I used the  factory method to create and get a post.

**12) WP’s post factory method will assign a value to a property** — When using the factory method to create and get a post object, there’s no need to assign a specific value to the ID property. WordPress will do that for you.

//Overwrites the post ID set with the factory method.
$post     = self::factory()->post->create_and_get();
$post->ID = 23;

//WordPress creates and gets the post object. Includes the ID,
$post = self::factory()->post->create_and_get();

**13) Allow the custom plugin to set the meta box ID in the nonce, not the meta-data module** — The meta_box store key set in the meta box config of each  custom plugin is used to set the meta_box_id for the nonce added to the custom fields. When integration testing the nonce in the function under test, let the custom plugin set the nonce ID, not ‘render_meta_box()’ That function handles the business logic of rendering the meta box in the WP Admin.

**14) Consolidation** — Consolidate variables, functions, or methods used repeatedly between tests.

**15) Initialize tests with `setUp()`** — Use the `setUp()` method as a place to initialize properties or methods shared between tests. By locating the init task into one location, each test receives a standardized set up environment in which perform it’s test. Initialized values can be changed within a particular test as needed.

**16) Reset stored data with `tearDown()`** — Use the `tearDown()` method to reset any data  structure reused between tests.

**17) Don’t forget the database during integration testing** —  Integration testing of stored meta_data assigned to a post_id must be loaded into the database before the function `render_meta_box` can be run. We added a private method `add_post_meta()` to the test class in order to load the mete_box_config stored in memory to the database. That allowed the test of `render_meta_box` to ensure that the correct meta data assigned to the post_id was returned.

**18) Wrap strings with single quotes to improve readability & formatting —**  Use single quotation marks around strings that include double quotation marks (e.g. strings of HTML). It’s easier to read, and avoids the need to escape double quotation marks inside the string.

**Pull request merged**
